cloudinary-community/cloudinary-util

- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/tests/plugins/overlays.spec.js
Updates and adds all styling parameter options available for text.
https://cloudinary.com/documentation/transformation_reference#l_text
Fixes #9 
See https://github.com/colbyfayock/next-cloudinary/issues/108
> Update Text Styling Parameters

- packages/util/src/index.ts
- packages/util/src/lib/cloudinary.ts
- packages/util/tests/lib/cloudinary.spec.js
Query parameters prevent parsing of the URL to to it being unaccounted for. This prevents this and reads the value into the URL parts in case the parameters are wanted to be used.
Fixes #15
> Fixes Query Param Breaking Parsing

- packages/url-loader/tests/lib/cloudinary.spec.js
Adds a test to capture URL source for URL generator
Partially doing this to trigger a new URL Loader release.
Fixes #15
> Adds Test for URL Loader Cloudinary URL

- packages/url-loader/src/constants/url.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/seo.ts
- packages/url-loader/src/plugins/version.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/util/src/lib/cloudinary.ts
- packages/util/tests/lib/cloudinary.spec.js
Cloudinary allows the ability to create SEO friendly URLs using the SEO Suffix option
This changes the asset type for example /image/upload => /images
This PR allows for the parsing of this and adds the ability to pass in an SEO suffix.
This also updates version management in how it parses and now allows someone to pass in a version
```
options: {
seoSuffix: 'my-friendly-url',
version: 1234
}
```
Fixes #18 
BREAKING CHANGES: "version" is returned as a number from parseUrl. "id" is now named "publicId" when returned from parseUrl
> Parse SEO URLs & SEO Suffix

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/cropping.spec.js
By default, when passing in a width, the URL generator returns a c_fill,w_[size] value based on the passed in width.
This generally works well to help define that value based on the width the caller wants, but if the raw transformations includes a value that conflicts with the size after, can create an error. This doesnt different from usual usage, but the expectation of how the props operate is that when you specify a width, you're going to specify dimensions and positioning relative to that
The example use case here is the Cloudinary Media Editor that may provide positioning and cropping based on the original image, which will create an issue if applied after this width.
Fixes #24 
Original Issue: https://github.com/colbyfayock/next-cloudinary/issues/149
> Fixes Raw Transformations Conflicting with Base Resize

- packages/util/src/lib/cloudinary.ts
- packages/util/tests/lib/cloudinary.spec.js
Previously parsing would fail with a `.` in a public ID
I wasn't sure how to solve this by changing the existing regex so I added an extra step to the parsing and first rip out the format if it exists, then continue on with the rest of the parsing.
Pulled all supported formats / extensions from cloudinary docs:
- https://cloudinary.com/documentation/image_transformations#image_format_support
- https://cloudinary.com/documentation/video_manipulation_and_delivery#supported_video_formats
Fixes #26
> Adds support for . in public ID

- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/colors.ts
- packages/url-loader/src/lib/transformations.ts
- packages/url-loader/src/plugins/effects.ts
- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/src/types/qualifiers.ts
- packages/url-loader/tests/plugins/effects.spec.js
- packages/url-loader/tests/plugins/overlays.spec.js
* Handles encoding special characters ,./ to avoid having to do it from the user side
* Creates a new concept of converters that allows qualifiers to transform values
* First use case is taking #color to rgb:color
Fixes #34
> Color converter, ,./ encoding

- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/video.ts
- packages/url-loader/src/plugins/zoompan.ts
- packages/url-loader/src/types/asset.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/src/types/video.ts
- packages/url-loader/tests/plugins/video.spec.js
Adds support for Streaming Profile via `sp_` including `sp_auto`
https://cloudinary.com/documentation/adaptive_bitrate_streaming#automatic_streaming_profile_selection
Additionally sets up video types to distinguish options
Fixes #39
> Video Types, Streaming Profile

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/video.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
`effects` was left in the video plugin file producing an error upstream
Next Cloudinary had a check for duplicate props but this library didn't
This fixes the duplicate effects but also adds the duplicate prop check and an effects test
Fixes #41
> Duplicate Props Does Not Throw Error - Effects Exists Twice

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/types/asset.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
Certain flags do not allow the inclusion of quality of auto.
To help get around this and rather than forcing an arbitrary value, this adds the ability to turn off quality and format by passing in the  value of `default` 
Fixes #46
> "default" turns off format and quality

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
No longer stores an instance of Cloudnary and creates a new one for each URL to avoid conflicting configurations
Fixes #48
> Fixes config conflicts

- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/plugins/fill-background.spec.js
Creates a new option of `fillBackground` that uses generative fill to fill in empty space when an image is padded.
Using `fillBackground` as is (resolves to true) uses the width and height applied to the <CldImage tag to add the aspect ratio transformation along with `b_gen_fill` and `c_pad` to create the desired shape. Cloudinary will then fill in the empty space, if any, with generative fill.
You can additionally pass in custom options, such as:
```
fillBackground: {
gravity: 'east',
prompt: 'pink and purple flowers',
crop: 'mpad'
}
```
Per the API: https://cloudinary.com/documentation/effects_and_artistic_enhancements#generative_fill
Fixes #56
> Generative Fill

- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/util/src/lib/cloudinary.ts
Decodes the Public ID to avoid double encoding after passing in to the URL Gen SDK, which encodes the value itself.
Fixes #59
> Decode Public ID to avoid double encoding

- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/remove-background.ts
- packages/url-loader/src/plugins/sanitize.ts
- packages/url-loader/src/plugins/video.ts
- packages/url-loader/src/plugins/zoompan.ts
- packages/url-loader/src/types/plugins.ts
Made `PluginSettings` a generic type, accepting type parameters to make plugin `options` more accurate.
I also updated the `options` type for some affected plugins:
- I added the `ImageOptions` type parameter for plugins with `assetTypes = ['image', 'images']`.
- I added the `VideoOptions` type parameter for plugins with `assetTypes = ['video', 'videos']`.
- I did not pass a type parameter for the plugins with `assetTypes = ['image', 'images', 'video', 'videos']`, so they should default to `AllOptions` instead.
Fixes #74
> Make PluginSettings generic

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/generative-replace.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/plugins/generative-replace.spec.js
Added Generative Replace. Can be utilized in one of two ways:
```js
{
replace: {
from: "apple",
to: "orange",
}
}
```
or
```js
{
replace: [ "apple", "orange" ]
}
```
Both options provide the preserve-geometry boolean parameter via the `preserveGeometry` property or as third option in the array.
This also includes 5 new tests for the plugin (and various ways of using it.)
Fixes #68
> feat: Generative Replace (#68)

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/named-transformations.ts
- packages/url-loader/src/types/asset.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
Adds support for strict transformations to `constructCloudinaryUrl` which prevents any transformations from being applied to the URL except named transformations.
Add `strictTransformations: true` when building the URL.
See added tests for examples.
Fixes #82
> Strict Transformations

- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/types/asset.ts
- packages/url-loader/tests/plugins/cropping.spec.js
Aspect Ratio is currently only supported in overlays and underlays which is incorrect.
This adds it as a top level option.
aspectRatio="16:9"
Fixes #87
And https://github.com/colbyfayock/next-cloudinary/issues/352
> Aspect Ratio as top level option

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/restore.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/restore.js
Adds the `restore` prop to enable generative restore
Fixes #70
> Generative Restore

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/remove.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/remove.spec.js
Adds support for generative remove
Syntax:
```
// One object
remove: 'apple'
// Multiple objects
remove: ['apple', 'banana', 'orange']
// Multiple instances of one object with shadow removed as well
remove: {
prompt: 'apple',
multiple: true,
removeShadow: true
}
// From a region
remove: {
region: [300, 200, 1900, 3500]
}
// From multiple regions
region: [
[300, 200, 1900, 3500],
[123, 321, 750, 500]
]
```
https://cloudinary.com/documentation/transformation_reference#e_gen_remove
Fixes #69
> Generative Remove

- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/tests/plugins/overlays.spec.js
This checks for the existence of an overlay effect qualifier before applying it.
Fixes #102
> Fixes undefined overlay effect qualifiers from being applied

- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
This adds the ability to apply positional qualifiers to effects and appliedEffects on overlays
```
effects: [{
shadow: 100,
x: 0,
y: 0
}]
```
Fixes #104
> Adds positional qualifiers to effects and appliedEffects

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
Updates the construct URL function to work properly when analytics is disabled.
Previous, passing the config.url.analytics as false would work, but not the analytics function option.
This normalizes behavior and makes sure it works as expected
Helps to address issue found: https://github.com/nuxt-modules/cloudinary/pull/174
> Fixes inability to turn off URL analytics 

- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/flags.ts
Starts work of migrating project to Zod allowing the ability ot use runtime Types to automatically generate documentation.
The hope is this can be used for Cloudinary Util docs as well as repurposing it for framework docs automations.
Fixes #50
>  Auto Generate Docs with Zod

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/abr.ts
- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/plugins/default-image.ts
- packages/url-loader/src/plugins/effects.ts
- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/flags.ts
- packages/url-loader/src/plugins/named-transformations.ts
- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/src/plugins/raw-transformations.ts
- packages/url-loader/src/plugins/recolor.ts
- packages/url-loader/src/plugins/remove-background.ts
- packages/url-loader/src/plugins/remove.ts
- packages/url-loader/src/plugins/replace.ts
- packages/url-loader/src/plugins/restore.ts
- packages/url-loader/src/plugins/sanitize.ts
- packages/url-loader/src/plugins/seo.ts
- packages/url-loader/src/plugins/underlays.ts
- packages/url-loader/src/plugins/version.ts
- packages/url-loader/src/plugins/zoompan.ts
- packages/url-loader/src/types/asset.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/src/types/video.ts
A change from `props` to `pluginProps` was inadvertently made inside internal plugin naming which had an effect on the plugins being exported and imported in consumer libraries.
Reverting this change to avoid it as a breaking change and wasn't intended.
Releasing this as a patch for 4.0.2 and will follow up as a patch with the commits on 4.1.0
> Reverting "pluginProps" to "props" in transformation plugins

- packages/url-loader/package.json
- pnpm-lock.yaml
This explciitly pins 1.15.0 for the URL Gen SDK to avoid installing 1.16.0
> Pin URL Gen 1.15.0

- packages/url-loader/src/constants/parameters.ts
- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/lib/transformations.ts
- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/zoompan.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/cropping.spec.js
- packages/url-loader/tests/plugins/fill-background.spec.js
This reworks cropping and resizing to support a bigger effort to correctly apply these transformations at the right point within the transformation string.
The current mechanism applies the core width and height to the front of the transformation string, with the idea of providing a "canvas" for someone to work from, but this is unintuitive, where a width and height would be the expected final resize, which may not be the case with other transformations (particularly dynamically generated responsive images).
This removes the widthResize property which applied the transformation the end, where the core width and height resizing now takes place.
To fill in for use cases where it made sense to apply a "base" cropping and resizing effect, a new `base*` property was added for width, height, …
> Reworking Resizing / Cropping

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
This searches the raw transformations on the cloudinary asset for f_ or q_ and if detected, doesn't set a new format or quality.
Fixes #146
> Fixes duplicate format or quality when added via Raw Transformations

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
If a raw transformation was passed in as `['f_auto/q_auto']`, it wouldnt be able to properly detect q_auto because of the joined `/` in the string. This adds additional parsing to split on the `/` first to enhance detection.
> Fixes f_ or q_ detection on rawTransformations

- packages/url-loader/package.json
- packages/url-loader/src/lib/video-player.ts
- packages/url-loader/src/types/config.ts
- packages/url-loader/tests/lib/video-player.spec.js
- pnpm-lock.yaml
This lifts the player options logic from Next Cloudinary, which should basically reflect Nuxt and Svelte.
This allows us to maintain a single set of configuration options for the player that will support each framework that creates a similar CldVideoPlayer component.
It would work as such:
```
const playerOptions = getVideoPlayerOptions(props, config);
videoPlayer(videoRef.current, playerOptions);
```
You can see some examples inside of the tests.
As of now, I left out `className` and `id` as returned options as the function's intent is to return "player options", which would be invalid values for the player. This in come cases could cause unintentional side effects, so opting to not return those.
A potential solution would be to return an object, with player options as a property, but …
> getVideoPlayerOptions

- packages/url-loader/CHANGELOG.md
- packages/url-loader/package.json
- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/video-player.ts
- packages/url-loader/src/types/config.ts
- packages/url-loader/tests/lib/video-player.spec.js
- pnpm-lock.yaml
This lifts the player options logic from Next Cloudinary, which should basically reflect Nuxt and Svelte.
This allows us to maintain a single set of configuration options for the player that will support each framework that creates a similar CldVideoPlayer component.
It would work as such:
```
const playerOptions = getVideoPlayerOptions(props, config);
videoPlayer(videoRef.current, playerOptions);
```
You can see some examples inside of the tests.
As of now, I left out `className` and `id` as returned options as the function's intent is to return "player options", which would be invalid values for the player. This in come cases could cause unintentional side effects, so opting to not return those.
A potential solution would be to return an object, with player options as a property, but …
> v5.3.0 - getVideoPlayerOptions

- packages/util/src/lib/cloudinary.ts
- packages/util/tests/lib/cloudinary.spec.js
URLs that include a CNAME are failing to be parsed. This makes the cloud name optional in cases where the hostname is not res.cloudinary.com to support that pattern.
Related https://github.com/cloudinary-community/next-cloudinary/issues/479
> Fixes Secure Distributions (CNAMEs) from not being parsed

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/replace-background.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/replace-background.spec.js
Adds the generative replace background feature
https://cloudinary.com/documentation/transformation_reference#e_gen_background_replace
* Boolean
```
replaceBackground
```
* String
```
replaceBackground="prompt"
```
* Object
```
replaceBackground={{
prompt: 'prompt',
seed: 2 // the ability to regenerate if you don't like the first one
}}
```
> Generative Replace Background

- packages/url-loader/src/lib/video-player.ts
- packages/url-loader/tests/lib/video-player.spec.js
When using getVideoPlayerOptions without a width or height, the returned options object would include an aspect ratio as `undefined:undefined`.
This checks to see the existence of the width and height values before trying to use them in the aspect ratio.
Fixes #176 
https://github.com/cloudinary-community/next-cloudinary/issues/499
> Fixes undefined aspect ratio `undefined:undefined` with no width or height

- packages/util/src/lib/cloudinary.ts
Adds back the delay that is present in next-cloudinary, to prevent spam requests
> fix: add delay to pollForProcessingImage

- packages/types/src/index.ts
I forgot to export the types I added in #191 - this also formats that index.ts file using default prettier settings
> fix: export the new widget types

- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/types/plugins.ts
- packages/url-loader/tests/plugins/cropping.spec.js
Adds the x and y coordinate options to the crop plugin to allow for coordinates based crops.
```
width: 123,
height: 321,
crop: {
type: 'crop',
x: 123
y: 321
}
```
https://github.com/cloudinary-community/next-cloudinary/issues/481
> Crop by X and Y Coordinates

- packages/types/src/index.ts
- packages/types/src/types/cloudinary-product-gallery.ts
This pull request introduces TypeScript types for the Cloudinary Product Gallery Widget. It defines a comprehensive interface for the widget, following the reference documentation for better type safety and improved developer experience. No additional dependencies are required for this change.
199 
Fixes #199
> Add TypeScript Types for Cloudinary Product Gallery Widget

- packages/url-loader/src/types/asset.ts
Add a list of allowable strings as an enum type for the format parameter.
Fixes #142
> feat: Add enum for format parameter

- packages/url-loader/src/plugins/abr.ts
- packages/url-loader/src/plugins/cropping.ts
- packages/url-loader/src/plugins/default-image.ts
- packages/url-loader/src/plugins/effects.ts
- packages/url-loader/src/plugins/enhance.ts
- packages/url-loader/src/plugins/extract.ts
- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/flags.ts
- packages/url-loader/src/plugins/named-transformations.ts
- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/src/plugins/preserve-transformations.ts
- packages/url-loader/src/plugins/raw-transformations.ts
- packages/url-loader/src/plugins/recolor.ts
- packages/url-loader/src/plugins/remove-background.ts
- packages/url-loader/src/plugins/remove.ts
- packages/url-loader/src/plugins/replace-background.ts
- packages/url-loader/src/plugins/replace.ts
- packages/url-loader/src/plugins/restore.ts
- packages/url-loader/src/plugins/sanitize.ts
- packages/url-loader/src/plugins/seo.ts
- packages/url-loader/src/plugins/underlays.ts
- packages/url-loader/src/plugins/version.ts
- packages/url-loader/src/plugins/zoompan.ts
similar to https://github.com/cloudinary-community/cloudinary-util/pull/227
> fix: make all individual plugin declarations tree-shakeable

- packages/url-loader/src/index.ts
> Force Major 6.0.0

- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/tests/plugins/fill-background.spec.ts
- pnpm-lock.yaml
Fixes #235
Cloudinary's [b_gen_fill transformation](https://cloudinary.com/documentation/transformation_reference#b_gen_fill) takes an optional `seed` parameter; this PR adds support for it. (And adds tests).
> feat: add seed parameter for b_gen_fill
