cloudinary-community/cloudinary-util

- packages/loader/src/plugins/cropping.ts
- packages/loader/tests/plugins/cropping.spec.js
Migrates fix from: https://github.com/colbyfayock/next-cloudinary/pull/113
Fixes #4
> Next Image Fill Support

- .github/workflows/release.yml
- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/src/plugins/overlays.ts
- packages/url-loader/src/types/qualifiers.ts
- packages/url-loader/tests/plugins/overlays.spec.js
- packages/util/src/index.ts
- packages/util/src/lib/util.ts
Updates the logic that handles adding text to an overlay to prevent breakage.
Defines order based on documentation:
https://cloudinary.com/documentation/transformation_reference#l_text
Fixes #8 
And https://github.com/colbyfayock/next-cloudinary/issues/107
> Improve Text Overlay Handling

- packages/url-loader/src/index.ts
Exports all the type for the URL loader
Fixes #11 
https://github.com/colbyfayock/next-cloudinary/issues/133
> Exporting Types

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/sanitize.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/lib/plugin/sanitize.spec.ts
> [Feature] sanitizer on the SVG image

- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/sanitize.spec.ts
Moves the test. Forcing URL Loader publish.
BREAKING CHANGES: SEE PR 19
> Sanitize Test

- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/tests/plugins/effects.spec.js
Adds radius effect (`r_#`)
Fixes #30
> Adding Radius

- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/types/analytics.ts
- packages/url-loader/src/types/config.ts
Exporting Analytics, Config, and other constructCloudinaryUrl props types
Fixes #32
> Exporting Analytics, Config, and other constructCloudinaryUrl props types

- packages/url-loader/package.json
- packages/url-loader/tests/lib/cloudinary.spec.js
- pnpm-lock.yaml
URL Gen includes a new analytics method that changes how we configure the different tracking IDs.
https://github.com/cloudinary/js-url-gen/pull/563
Updates the package and fixes the tests.
This is more relevant in terms of usage by packages that use the URL Loader
> Updated Analytics

- packages/url-loader/tests/plugins/remove-background.spec.js
Adding test for removing background. 
This is in reference to this issue here: https://github.com/colbyfayock/next-cloudinary/issues/21
> Adding test for remove background

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/default-image.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/default.spec.js
- pnpm-lock.yaml
Adds support for providing a defaultImage (`d_publicid`) when creating an image URL
Supports Next Cloudinary: https://github.com/colbyfayock/next-cloudinary/issues/340
> Default Image

- .github/workflows/release.yml
> adding 16 to tests

- packages/util/package.json
> release from beta

- packages/url-loader/package.json
> remove main only releases

- packages/url-loader/.releaserc
- packages/url-loader/package.json
- pnpm-lock.yaml
> trying semantic release npm

- packages/url-loader/package.json
- pnpm-lock.yaml
> reverting npm semrelease version

- packages/url-loader/package.json
- pnpm-lock.yaml
> updating semrel pnpm

- packages/url-loader/.releaserc
> reverting back to pnpm

- packages/url-loader/package.json
- pnpm-lock.yaml
> Beta+test2

- packages/url-loader/.releaserc
- packages/url-loader/package.json
- pnpm-lock.yaml
> publish branch

- packages/url-loader/package.json
- pnpm-lock.yaml
> last time tongiht

- packages/url-loader/src/plugins/named-transformations.ts
Trying to force a major release
> Deprecation description for namedTransformations

- packages/url-loader/src/plugins/named-transformations.ts
> Deprecation Warning for transformations prop

- packages/url-loader/CHANGELOG.md
- packages/url-loader/src/plugins/raw-transformations.ts
> Descriptions

- packages/util/src/lib/cloudinary.ts
> Moves normalizeNumberParameter to Util

- packages/url-loader/src/lib/cloudinary.ts
> Description - force patch

- packages/url-loader/package.json
- packages/url-loader/tests/lib/cloudinary.spec.js
- pnpm-lock.yaml
Upgrades the URL Gen SDK to bring in changes to fix encoding issues with commas in public ID.
Merging this into branch `loader-v3.26.0` which will be manually released.
Fixes core issue with: https://github.com/cloudinary-community/next-cloudinary/issues/414
> v3.26.0 - Upgrade URL Gen

- packages/url-loader/package.json
- packages/url-loader/tests/lib/cloudinary.spec.js
- pnpm-lock.yaml
Updates Cloudinary URL Gen SDK to pull in updates and fixes.
These changes were released on 3.26.1 via https://github.com/colbyfayock/cloudinary-util/tree/loader-v3.26.1
> Update URL Gen SDK

- packages/types/.releaserc
- packages/types/CHANGELOG.md
- packages/types/README.md
- packages/types/package.json
- packages/types/src/index.d.ts
- packages/types/src/types/cloudinary-upload-widget.d.ts
- packages/types/src/types/cloudinary-video-player.d.ts
- pnpm-lock.yaml
Creates a new package that exports types for Cloudinary widgets and integrations that don't support native modules or types.
Package will be available via `@cloudianary-util/types`
Types added:
- Cloudinary Upload Widget
- Cloudinary Video Player
Fixes #122
> Types Package

- packages/url-loader/src/constants/qualifiers.ts
- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/src/plugins/effects.ts
- packages/url-loader/src/plugins/enhance.ts
- packages/url-loader/src/plugins/fill-background.ts
- packages/url-loader/src/plugins/zoompan.ts
- packages/url-loader/src/types/image.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/plugins/cropping.spec.js
- packages/url-loader/tests/plugins/fill-background.spec.js
- packages/url-loader/tests/plugins/zoompan.spec.js
Adds a few different features and fixes including:
- Adds `enhance`
- Adds `angle` as a top-level effect, also available in the `effects` array
- Adds `loop` as a top-level effect
- Adds a test and console warning for fill background without sizing
- Fixes zoompan bug with custom options
Fixes #140
Fixes #91 
Fixes #100
> AI Enhance, Angle, Fixes zoompan, Misc Fixes / Tests

- packages/url-loader/src/types/asset.ts
Adds type of string for quality prop
Fixes #148
> Fixes Quality String Type

- packages/url-loader/src/index.ts
- packages/url-loader/src/lib/video-player.ts
> getVideoPlayerOptions Exports

- packages/url-loader/src/lib/video-player.ts
Public ID (or url) is required via the src prop for the video player. To avoid player issues, throw error if not present.
> Throw error if no public ID for video player options

- packages/url-loader/src/index.ts
- packages/url-loader/src/types/config.ts
> Using /types to import Config Options

- packages/types/package.json
- packages/url-loader/package.json
- packages/util/package.json
Adds the repo information to the package so you can easily get here from NPM
> chore: add repo information to package

- packages/util/src/index.ts
- packages/util/src/lib/cloudinary.ts
- tsconfig.json
> feat: add pollForProcessingImage

- packages/util/src/lib/cloudinary.ts
> refactor: update pollForProcessingImage style

- packages/types/src/types/cloudinary-upload-widget.ts
Add more types for upload widget
> feat: add more upload widget types

- packages/url-loader/src/lib/cloudinary.ts
- packages/url-loader/tests/lib/cloudinary.spec.js
- packages/url-loader/tests/lib/video-player.spec.js
> fix: default the version to 1 when constructing a cld url

- packages/types/src/index.ts
- packages/types/src/types/cloudinary-video-player.ts
> feat: add video player types

- packages/types/src/types/cloudinary-video-player.ts
Added an Object "videojs" in interface CloudinaryVideoPlayer 
https://github.com/cloudinary-community/next-cloudinary/issues/426
> Fix: For removing ts-ignore in CldVideoPlayer

- packages/types/src/types/cloudinary-video-player.ts
Added cloudinaryAnalytics to Video Player types
Fixes #171
> Add cloudinaryAnalytics to Video Player types #171

- packages/util/src/lib/cloudinary.ts
solving the following issue listed in next-cloudinary 
Issue link : https://github.com/cloudinary-community/next-cloudinary/issues/512 
@colbyfayock
> Log X-Cld-Error header in dev mode

- packages/util/src/lib/util.ts
BREAKING CHANGES: previously changed signature of pollForProcessingImage
> Change to Force Deploy
